#!/bin/sh

if [ -z "$1" ]; then
    echo "Add message"
    exit 1
fi

zip -r submission.csv.zip submission.csv

kaggle competitions submit -c ieee-fraud-detection -f submission.csv  -m "$1"

rm submission.csv.zip
